namespace SolutionName.DataModels.Models;

using SolutionName.Abstractions.DataModels;

/// <summary>
/// Spike demonstration for web-template#79. The entire property implementation
/// of <see cref="ISampleContract"/> is generated by ConcreteFromInterfaceGenerator
/// into the companion partial — this file is the whole hand-written concrete.
/// </summary>
public partial class SampleContract : ISampleContract;
