using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SolutionName.SourceGenerators;

/// <summary>
/// Generates the trivial data-property implementation for any <c>partial class</c>
/// that implements an interface marked <c>[GenerateConcrete]</c>.
///
/// The interface (the contract) is hand-authored in Abstractions; the author
/// declares a one-line partial stub in whichever project should own the concrete
/// (<c>public partial class Foo : IFoo;</c>), and this generator fills the
/// property boilerplate onto the companion partial. Properties already provided
/// by a base class or declared by the author are left untouched, so
/// behaviour-carrying domain models keep working.
/// </summary>
[Generator]
public sealed class ConcreteFromInterfaceGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateConcreteAttribute";

    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, _) =>
                    (INamedTypeSymbol?)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) => Emit(spc, symbol!));
    }

    private static bool IsCandidate(SyntaxNode node)
        => node is ClassDeclarationSyntax cls
           && cls.BaseList is not null
           && cls.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));

    private static void Emit(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var markedInterfaces = classSymbol.Interfaces
            .Where(HasGenerateConcreteAttribute)
            .ToImmutableArray();
        if (markedInterfaces.IsEmpty)
        {
            return;
        }

        // Every property across the marked interfaces and the interfaces they
        // extend, deduped by name.
        var interfaceProps = markedInterfaces
            .SelectMany(i => i.AllInterfaces.Add(i))
            .SelectMany(i => i.GetMembers().OfType<IPropertySymbol>())
            .GroupBy(p => p.Name)
            .Select(g => g.First())
            .ToImmutableArray();

        var alreadyProvided = InheritedOrDeclaredPropertyNames(classSymbol);
        var toEmit = interfaceProps
            .Where(p => !alreadyProvided.Contains(p.Name))
            .ToImmutableArray();
        if (toEmit.IsEmpty)
        {
            return;
        }

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(classSymbol.Name);
        sb.AppendLine("{");
        foreach (var prop in toEmit)
        {
            var type = prop.Type.ToDisplayString(TypeFormat);
            var accessors = prop.SetMethod is not null ? "{ get; set; }" : "{ get; init; }";
            var initializer = InitializerFor(prop.Type);
            sb.Append("    public ").Append(type).Append(' ').Append(prop.Name)
              .Append(' ').Append(accessors).Append(initializer).AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource(
            $"{classSymbol.Name}.Concrete.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool HasGenerateConcreteAttribute(INamedTypeSymbol iface)
        => iface.GetAttributes().Any(a => a.AttributeClass?.Name == AttributeName);

    private static ImmutableHashSet<string> InheritedOrDeclaredPropertyNames(INamedTypeSymbol classSymbol)
    {
        var names = ImmutableHashSet.CreateBuilder<string>();

        // Properties the author wrote directly on the partial.
        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            names.Add(member.Name);
        }

        // Properties supplied by a base class (e.g. a domain model extending a data model).
        var baseType = classSymbol.BaseType;
        while (baseType is not null && baseType.SpecialType != SpecialType.System_Object)
        {
            foreach (var member in baseType.GetMembers().OfType<IPropertySymbol>())
            {
                names.Add(member.Name);
            }

            baseType = baseType.BaseType;
        }

        return names.ToImmutable();
    }

    private static string InitializerFor(ITypeSymbol type)
    {
        if (IsCollectionType(type))
        {
            return " = [];";
        }

        // Non-nullable reference types need a value to satisfy CS8618; the
        // generator can't know a semantic default, so suppress with default!.
        if (type.IsReferenceType && type.NullableAnnotation != NullableAnnotation.Annotated)
        {
            return " = default!;";
        }

        return string.Empty;
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol)
        {
            return true;
        }

        if (type is not INamedTypeSymbol named || !named.IsGenericType)
        {
            return false;
        }

        switch (named.ConstructedFrom.Name)
        {
            case "IReadOnlyList":
            case "IReadOnlyCollection":
            case "IEnumerable":
            case "IList":
            case "ICollection":
            case "List":
                return true;
            default:
                return false;
        }
    }
}
