using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SolutionName.SourceGenerators;

/// <summary>
/// Mirrors a concrete class's public surface into an interface.
/// <c>[GenerateInterface] class Status</c> emits <c>interface IStatus</c> in the
/// same namespace; you then write <c>: IStatus</c> on the class yourself.
/// </summary>
/// <remarks>
/// Direction matters: the class holds the method bodies, so mirroring *down* to
/// an interface is total — every public member has an obvious signature and
/// nothing has to be invented. (The reverse direction can only ever handle
/// property-shaped members; see #83.)
/// </remarks>
[Generator]
public sealed class InterfaceFromConcreteGenerator : IIncrementalGenerator
{
    private const string AttributeName = "GenerateInterfaceAttribute";

    // Fully-qualified, with nullable annotations, so the generated file never
    // depends on which usings happen to be in scope.
    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor NestedTypeUnsupported = new(
        id: "SNGEN001",
        title: "[GenerateInterface] does not support nested classes",
        messageFormat: "'{0}' is a nested class; move it to its own namespace-level type to generate an interface for it",
        category: "SolutionName.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor StaticTypeUnsupported = new(
        id: "SNGEN002",
        title: "[GenerateInterface] cannot be applied to a static class",
        messageFormat: "'{0}' is static, so it has no instance surface to mirror",
        category: "SolutionName.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null && HasGenerateInterfaceAttribute(symbol))
            .Select(static (symbol, _) => symbol!);

        context.RegisterSourceOutput(classes, static (spc, symbol) => Emit(spc, symbol));
    }

    private static bool HasGenerateInterfaceAttribute(INamedTypeSymbol symbol)
        => symbol.GetAttributes().Any(a => a.AttributeClass?.Name == AttributeName);

    private static void Emit(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        if (classSymbol.ContainingType is not null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                NestedTypeUnsupported, classSymbol.Locations.FirstOrDefault(), classSymbol.Name));
            return;
        }

        if (classSymbol.IsStatic)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                StaticTypeUnsupported, classSymbol.Locations.FirstOrDefault(), classSymbol.Name));
            return;
        }

        var interfaceName = "I" + classSymbol.Name;
        var accessibility = classSymbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";

        // If the base class is itself mirrored, inherit its interface and emit
        // only what this class adds. Otherwise fold the inherited surface in,
        // or the interface would be an incomplete view of the class.
        var mirroredBase = FindMirroredBase(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(accessibility).Append(" interface ").Append(interfaceName);
        AppendTypeParameters(sb, classSymbol.TypeParameters);

        if (mirroredBase is not null)
        {
            sb.Append(" : ").Append(MirrorNameOf(mirroredBase));
        }

        sb.AppendLine();
        AppendConstraints(sb, classSymbol.TypeParameters);
        sb.AppendLine("{");

        foreach (var member in CollectMembers(classSymbol, mirroredBase))
        {
            AppendMember(sb, member);
        }

        sb.AppendLine("}");

        // Type parameters make the name ambiguous on their own; arity keeps the
        // generated hint name unique within the compilation.
        var hint = classSymbol.TypeParameters.Length > 0
            ? $"{classSymbol.Name}_{classSymbol.TypeParameters.Length}.Interface.g.cs"
            : $"{classSymbol.Name}.Interface.g.cs";

        context.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// The nearest base class that also carries [GenerateInterface], if any.
    /// Its mirror interface becomes this interface's base, so shared members
    /// are declared exactly once.
    /// </summary>
    private static INamedTypeSymbol? FindMirroredBase(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;
        while (baseType is not null && baseType.SpecialType != SpecialType.System_Object)
        {
            if (HasGenerateInterfaceAttribute(baseType.OriginalDefinition))
            {
                return baseType;
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    /// <summary>
    /// Renders the mirror-interface reference for a (possibly constructed)
    /// base type: <c>CustomerBase&lt;Address&gt;</c> becomes
    /// <c>global::Ns.ICustomerBase&lt;global::Ns.Address&gt;</c>.
    /// </summary>
    private static string MirrorNameOf(INamedTypeSymbol baseType)
    {
        var ns = baseType.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : "global::" + baseType.ContainingNamespace.ToDisplayString() + ".";

        var name = ns + "I" + baseType.Name;

        if (baseType.TypeArguments.Length == 0)
        {
            return name;
        }

        var args = baseType.TypeArguments.Select(t => t.ToDisplayString(TypeFormat));
        return name + "<" + string.Join(", ", args) + ">";
    }

    /// <summary>
    /// Public instance members to mirror. Walks up the base chain until it hits
    /// a mirrored base (whose interface we inherit instead) or object.
    /// </summary>
    private static IEnumerable<ISymbol> CollectMembers(
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol? mirroredBase)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var results = new List<ISymbol>();

        var current = (INamedTypeSymbol?)classSymbol;
        while (current is not null && current.SpecialType != SpecialType.System_Object)
        {
            if (mirroredBase is not null &&
                SymbolEqualityComparer.Default.Equals(current, mirroredBase))
            {
                break;
            }

            foreach (var member in current.GetMembers())
            {
                if (!ShouldMirror(member))
                {
                    continue;
                }

                // Dedupe by signature so an override and the member it overrides
                // collapse to one declaration — the most-derived wins, because
                // the derived type is visited first.
                var key = SignatureKey(member);
                if (seen.Add(key))
                {
                    results.Add(member);
                }
            }

            current = current.BaseType;
        }

        return results;
    }

    private static bool ShouldMirror(ISymbol member)
    {
        if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic)
        {
            return false;
        }

        // Interfaces cannot declare fields, and an explicit implementation is
        // already tied to another interface.
        if (member.IsImplicitlyDeclared)
        {
            return false;
        }

        switch (member)
        {
            case IPropertySymbol property:
                // An indexer or property is mirrored only if at least one
                // accessor is public.
                return property.GetMethod?.DeclaredAccessibility == Accessibility.Public
                    || property.SetMethod?.DeclaredAccessibility == Accessibility.Public;

            case IEventSymbol:
                return true;

            case IMethodSymbol method:
                if (method.MethodKind != MethodKind.Ordinary)
                {
                    // Excludes constructors, operators, destructors, and the
                    // accessor methods already covered by their property.
                    return false;
                }

                if (method.ExplicitInterfaceImplementations.Length > 0)
                {
                    return false;
                }

                // object's virtuals are on every type; restating them in an
                // interface is noise. Test what the method actually OVERRIDES,
                // not its name — a user-defined Equals(MyType) is a real
                // member and must survive.
                return !OverridesObjectMember(method);

            default:
                return false;
        }
    }

    /// <summary>
    /// True when the method is an override of one of System.Object's virtuals.
    /// </summary>
    /// <remarks>
    /// Deliberately does NOT walk <see cref="IMethodSymbol.OverriddenMethod"/>:
    /// inside a generator that property is null even when
    /// <see cref="ISymbol.IsOverride"/> is true, so a walk silently matches
    /// nothing and every ToString/Equals/GetHashCode leaks into the interface.
    /// Matching IsOverride AND the signature is both reliable and narrow — a
    /// user-defined <c>Equals(MyType)</c> is not an override, so it survives.
    /// </remarks>
    private static bool OverridesObjectMember(IMethodSymbol method)
    {
        if (!method.IsOverride)
        {
            return false;
        }

        return method.Name switch
        {
            "ToString" or "GetHashCode" => method.Parameters.Length == 0,
            "Equals" => method.Parameters.Length == 1
                && method.Parameters[0].Type.SpecialType == SpecialType.System_Object,
            _ => false,
        };
    }

    private static string SignatureKey(ISymbol member) => member switch
    {
        IMethodSymbol m =>
            "M:" + m.Name + "`" + m.TypeParameters.Length + "(" +
            string.Join(",", m.Parameters.Select(p => p.Type.ToDisplayString(TypeFormat))) + ")",
        IPropertySymbol p when p.IsIndexer =>
            "X:(" + string.Join(",", p.Parameters.Select(q => q.Type.ToDisplayString(TypeFormat))) + ")",
        _ => member.Kind + ":" + member.Name,
    };

    private static void AppendMember(StringBuilder sb, ISymbol member)
    {
        switch (member)
        {
            case IPropertySymbol property:
                AppendProperty(sb, property);
                break;
            case IEventSymbol evt:
                sb.Append("    event ").Append(evt.Type.ToDisplayString(TypeFormat))
                  .Append(' ').Append(evt.Name).AppendLine(";");
                break;
            case IMethodSymbol method:
                AppendMethod(sb, method);
                break;
        }
    }

    private static void AppendProperty(StringBuilder sb, IPropertySymbol property)
    {
        sb.Append("    ").Append(property.Type.ToDisplayString(TypeFormat)).Append(' ');

        if (property.IsIndexer)
        {
            sb.Append("this[");
            AppendParameters(sb, property.Parameters);
            sb.Append(']');
        }
        else
        {
            sb.Append(property.Name);
        }

        sb.Append(" { ");

        if (property.GetMethod?.DeclaredAccessibility == Accessibility.Public)
        {
            sb.Append("get; ");
        }

        // `init` is part of the contract: an interface declaring `set` would let
        // callers mutate a type the author made init-only.
        if (property.SetMethod?.DeclaredAccessibility == Accessibility.Public)
        {
            sb.Append(property.SetMethod.IsInitOnly ? "init; " : "set; ");
        }

        sb.AppendLine("}");
    }

    private static void AppendMethod(StringBuilder sb, IMethodSymbol method)
    {
        sb.Append("    ").Append(method.ReturnType.ToDisplayString(TypeFormat))
          .Append(' ').Append(method.Name);

        AppendTypeParameters(sb, method.TypeParameters);

        sb.Append('(');
        AppendParameters(sb, method.Parameters);
        sb.Append(')');

        if (method.TypeParameters.Length > 0)
        {
            sb.AppendLine();
            AppendConstraints(sb, method.TypeParameters, indent: "        ");
            sb.AppendLine("        ;");
            return;
        }

        sb.AppendLine(";");
    }

    private static void AppendParameters(StringBuilder sb, ImmutableArray<IParameterSymbol> parameters)
    {
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            var p = parameters[i];

            switch (p.RefKind)
            {
                case RefKind.Ref: sb.Append("ref "); break;
                case RefKind.Out: sb.Append("out "); break;
                case RefKind.In: sb.Append("in "); break;
            }

            if (p.IsParams)
            {
                sb.Append("params ");
            }

            sb.Append(p.Type.ToDisplayString(TypeFormat)).Append(' ').Append(p.Name);

            if (p.HasExplicitDefaultValue)
            {
                sb.Append(" = ").Append(FormatDefault(p.ExplicitDefaultValue, p.Type));
            }
        }
    }

    private static string FormatDefault(object? value, ITypeSymbol type) => value switch
    {
        null => type.IsValueType ? "default" : "null",
        bool b => b ? "true" : "false",
        string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        char c => "'" + c + "'",
        _ => System.Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "default",
    };

    private static void AppendTypeParameters(StringBuilder sb, ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.Length == 0)
        {
            return;
        }

        sb.Append('<').Append(string.Join(", ", typeParameters.Select(t => t.Name))).Append('>');
    }

    /// <summary>
    /// Copies constraints verbatim. This is what makes the generic layering
    /// work: <c>where TAddress : IAddress</c> is the abstraction that lets one
    /// consumer serve both the contract and the domain model.
    /// </summary>
    private static void AppendConstraints(
        StringBuilder sb,
        ImmutableArray<ITypeParameterSymbol> typeParameters,
        string indent = "    ")
    {
        foreach (var tp in typeParameters)
        {
            var parts = new List<string>();

            if (tp.HasReferenceTypeConstraint)
            {
                parts.Add("class");
            }

            if (tp.HasValueTypeConstraint)
            {
                parts.Add("struct");
            }

            if (tp.HasNotNullConstraint)
            {
                parts.Add("notnull");
            }

            if (tp.HasUnmanagedTypeConstraint)
            {
                parts.Add("unmanaged");
            }

            parts.AddRange(tp.ConstraintTypes.Select(t => t.ToDisplayString(TypeFormat)));

            // `new()` must come last.
            if (tp.HasConstructorConstraint)
            {
                parts.Add("new()");
            }

            if (parts.Count == 0)
            {
                continue;
            }

            sb.Append(indent).Append("where ").Append(tp.Name).Append(" : ")
              .AppendLine(string.Join(", ", parts));
        }
    }
}
